language: scala
scala:
- 2.10.6
- 2.11.7
jdk:
- oraclejdk7
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
script:
- sbt ++$TRAVIS_SCALA_VERSION coverage test doc
after_success:
- bash <(curl -s https://codecov.io/bash)
